### ISSUE TITLE
Error while creating job: job job-executor-service-job- failed

### ISSUE THREAD

**Issue by afzal442** [afzal442/keptn-pg-killerway#68] opened 2022-10-28 18:43 UTC
![image](https://user-images.githubusercontent.com/11625672/198709082-af33c1f6-cc0c-4306-a63e-215044a03b7c.png)

Hi @agardnerIT can you address this issue if I you have faced it?

Reason: BackoffLimitExceeded

**Comment by agardnerIT** [comment] 2022-12-08 00:39
I'm afraid I cannot reproduce this. Closing as a transient Killercoda (environment) caused issue. Please re-open this thread if more reports come in and thank you to the reporter (whomever it was) for taking the time to report this :)

**Closed by agardnerIT** 2022-12-08 00:39 UTC
